model_list:
  # OpenAI Models
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: openai/gpt-3.5-turbo
      api_key: os.environ/OPENAI_API_KEY

  # OpenRouter Models
  - model_name: openrouter-gpt-4o
    litellm_params:
      model: openrouter/gpt-4o
      api_key: os.environ/OPENROUTER_API_KEY
  - model_name: openrouter-claude-3-5-sonnet
    litellm_params:
      model: openrouter/anthropic/claude-3-5-sonnet-20241022
      api_key: os.environ/OPENROUTER_API_KEY
  - model_name: openrouter-gemini-2-flash
    litellm_params:
      model: openrouter/google/gemini-2.0-flash
      api_key: os.environ/OPENROUTER_API_KEY

  # Google Gemini Models
  - model_name: gemini-2-flash
    litellm_params:
      model: gemini/gemini-2.0-flash-001
      api_key: os.environ/GOOGLE_API_KEY
  - model_name: gemini-2-flash-exp
    litellm_params:
      model: gemini/gemini-2.0-flash-exp
      api_key: os.environ/GOOGLE_API_KEY

litellm_settings:
  set_verbose: true
  success_callback: []
  failure_callback: []

general_settings:
  master_key: "sk-1234"
  database_url: "postgresql://user:password@db:5432/stratlogic"
  default_model: "openrouter-gpt-4o"
  default_provider: "openrouter"
